"""
Spotify Real-time Lyrics Streamer - Host Controller
Author: Robi Gusmery
License: Mozilla Public License 2.0 (MPL 2.0)
Description: Synchronizes with Spotify Web API to poll active playback states,
             extracts track lyrics via Genius API, and streams formatted text
             buffers downstream over Serial to an Arduino hardware display.
"""

import time
import sys
import serial
import lyricsgenius
import spotipy
from spotipy.oauth2 import SpotifyOAuth

# ==============================================================================
#                          CONFIGURATION SUBSYSTEM
# ==============================================================================
# Inject your secure API credentials and hardware port mapping targets below.
# WARNING: De-initialize these tokens before pushing commits to public repositories.

GENIUS_TOKEN = "YOUR_GENIUS_API_TOKEN"
ARDUINO_PORT = 'COM3'  # Windows: 'COMX' | Linux/macOS: '/dev/ttyUSBX' or '/dev/ttyACMX'
BAUD_RATE = 115200

SPOTIPY_CLIENT_ID = "YOUR_SPOTIFY_CLIENT_ID"
SPOTIPY_CLIENT_SECRET = "YOUR_SPOTIFY_CLIENT_SECRET"
SPOTIPY_REDIRECT_URI = "https://localhost:8888/callback"
# ==============================================================================

# Initialize Serial Communication Hardware Interface
try:
    arduino = serial.Serial(port=ARDUINO_PORT, baudrate=BAUD_RATE, timeout=.1)
    print(f"✓ [HARDWARE] Established Serial connection on interface {ARDUINO_PORT}")
except Exception as serial_exception:
    print(f"✗ [HARDWARE] Link allocation failed on port {ARDUINO_PORT}: {serial_exception}")
    sys.exit(1)

# Initialize Genius API Engine Instance
genius = lyricsgenius.Genius(GENIUS_TOKEN)
genius.remove_section_headers = True  # Strips structural tags like [Chorus], [Verse]

# Initialize Spotify Web API Client with OAuth 2.0 Authorization Code Flow
try:
    spotify_auth_manager = SpotifyOAuth(
        client_id=SPOTIPY_CLIENT_ID,
        client_secret=SPOTIPY_CLIENT_SECRET,
        redirect_uri=SPOTIPY_REDIRECT_URI,
        scope="user-read-currently-playing"
    )
    spotify_client = spotipy.Spotify(auth_manager=spotify_auth_manager)
    print("✓ [SPOTIFY] Authentication Manager initialized successfully.")
except Exception as auth_exception:
    print(f"✗ [SPOTIFY] Authentication flow setup failed: {auth_exception}")
    sys.exit(1)


def fetch_normalized_lyrics(title: str, artist: str) -> list or None:
    """
    Queries the Genius backend API, isolates the lyrics payload, performs text 
    normalization routines, and strips out specific analytics/embedded tags.
    """
    try:
        print(f"🔍 [GENIUS] Querying remote database for: {title} - {artist}")
        song = genius.search_song(title, artist)
        if song:
            # Parse block array and drop whitespace-only lines
            raw_lines = [line.strip() for line in song.lyrics.split('\n') if line.strip()]
            if raw_lines:
                raw_lines.pop(0)  # Drop the initial artifact title line generated by Genius
            return raw_lines
    except Exception as api_error:
        print(f"✗ [GENIUS] API transaction exception occurred: {api_error}")
    return None


# Orchestration Event Loop State Variables
current_track_id = ""
active_lyrics_buffer = []
current_lyric_index = 0

print("\n🚀 [SYSTEM] Orchestrator Engine Active. Awaiting active Spotify Media Session...")

while True:
    try:
        # Request active playback state payload from the Spotify server cluster
        playback_state = spotify_client.currently_playing()
        
        if playback_state and playback_state['is_playing']:
            track_item = playback_state['item']
            track_id = track_item['id']
            track_title = track_item['name']
            track_artist = track_item['artists'][0]['name']
            
            # Context-Switch Handler: Intercept Track Changes
            if track_id != current_track_id:
                current_track_id = track_id
                print(f"\n🎵 [TRACK EVENT] Intercepted Switch: '{track_title}' by {track_artist}")
                
                # Transmit initial visual state payload downstream to hardware LCD
                # Truncates title buffer to fit 16 characters on the first line
                arduino.write(f"Playing:\n{track_title[:16]}\n".encode('utf-8'))
                
                # Pull new lyrics set and reset buffer control indices
                active_lyrics_buffer = fetch_normalized_lyrics(track_title, track_artist)
                current_lyric_index = 0
                
                if not active_lyrics_buffer:
                    print("⚠️ [DATA] Lyrics payload returned empty for this track profile.")
                    arduino.write("Lyrics Not\nFound\n".encode('utf-8'))

            # Downstream Streaming Pipeline Controller
            if active_lyrics_buffer and current_lyric_index < len(active_lyrics_buffer):
                target_line = active_lyrics_buffer[current_lyric_index]
                
                # Data Scrubbing: Strip potential trailer scraping text ("12Embed", "ContributeEmbed")
                if "Embed" in target_line:
                    target_line = target_line.split("Embed")[0]
                
                # Check for empty string post-scrubbing routine
                if target_line.strip():
                    print(f"📟 [SERIAL TRANSMIT] Sending Buffer: {target_line}")
                    # Pipe data string across serial bus with standard Unix terminator
                    arduino.write(f"{target_line}\n".encode('utf-8'))
                    current_lyric_index += 1
                    time.sleep(4)  # Global line display duration on hardware LCD
                else:
                    current_lyric_index += 1
            else:
                # Idle delay if track lyrics stream completes before track end
                time.sleep(2)
        else:
            print("💤 [SYSTEM] Awaiting active playback session metrics...", end="\r")
            time.sleep(2)

    except KeyboardInterrupt:
        print("\n🛑 [SHUTDOWN] Process terminated gracefully by SIGINT signal request.")
        break
    except Exception as system_runtime_error:
        print(f"\n🚨 [CRITICAL RUNTIME ERROR]: {system_runtime_error}")
        time.sleep(2)
